### ISSUE TITLE
sample ui-router example code is not work

### ISSUE THREAD

**Issue by kuma0605** [laurelnaiad/angular-couch-potato#3]
error.
I think that the dependencies is too new.But the relevant code is not matching.
May be I need add angular-router into html.
Whatever, I hope you can fix it.

**Comment by laurelnaiad** [comment]
Yup, you're right -- when I released that version everything was compatible but the world shifted a little bit (and I missed some changes in the readme.  Thanks for putting together a sample that works with the latest.  I'll need to figure out how to set the npm dependencies more carefully since ui-router 2 and more importantly angular 1.2 are still moving targets.  Glad you figured out how to make it work!
